name: 'Publish reddit stylesheet'
description: 'Publish a reddit stylesheet to a subreddit'
branding:
  icon: 'image'
  color: 'blue'
inputs:
  subreddit:
    description: 'Subreddit to publish to'
    required: true
  path:
    description: 'Path to theme files'
    required: true
  clear:
    description: 'Clear style and images before uploading'
    required: false
    default: false
  cleanup:
    description: 'Remove unused images'
    required: false
    default: false
  skip images:
    description: 'Skip uploading of images'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subreddit }}
    - ${{ inputs.path }}
